#!/bin/sh

# takes no arguments, 
# updates the ./pluto.frm and ./boot.frm from the PlutoSDR firmware
# on a linix machine. Tested on debian.
# also assumes a default ./ssh/config file for Pluto (per the wiki)

HOST=plutosdr

wait_for_pluto()
{
wait=0.5
time=$(echo $1 / $wait | bc)
i=0
until grep -qs 'PlutoSDR' /proc/mounts ;
do
  if [ "`ls -l /dev/disk/by-label/ 2>/dev/null | grep PlutoSDR | wc -l`" != "0" ] ; then
    # try to mount it
    udisksctl mount -b /dev/$(ls -l /dev/disk/by-label/ | grep PlutoSDR | awk -F/ '{print $NF}') > /dev/null 2>&1
  fi
  sleep $wait
  i=$(expr $i + 1)
  if [ "$i" -gt "$time" ] ; then
    echo timed out $i
    exit
  fi
done

dev=/dev/$(ls -l /dev/disk/by-label/ 2>/dev/null | grep PlutoSDR  | awk -F "/" '{print $NF}' | sed -e 's:[0-9]$::')
disk=$(grep ${dev} /proc/mounts | awk '{print $2}')

# network can come up much later, and we need to wait for that as well
wait=$(echo "$wait * 1000" | bc)
while ! ping -c 1 -w $wait 192.168.2.1 2>&1 > /dev/null
do
  i=$(expr $i + 1)
  if [ "$i" -gt "$time" ] ; then
    echo timed out $i
    exit
  fi
done
}

ssh_cmd()
{
sshpass -panalog ssh $HOST "$1" 2>/dev/null
if [ "$?" -ne "0" ] ; then
  echo ssh command $1 failed
  exit
fi
}

reset_pluto()
{
echo resetting pluto at ${dev} ${disk} $HOST
ssh_cmd '/usr/sbin/pluto_reboot reset'
sleep 3
wait_for_pluto 10
}

command sshpass >/dev/null 2>&1
if [ "$?" -ne "0" ] ; then
  echo sorry, your distribution needs to have 'sshpass' installed
  echo try \'sudo apt-get install sshpass\' OR \'sudo yum install sshpass\'
  exit
fi

#Make sure a device is plugged in, and you can find it
wait_for_pluto 30

dd if=${dev} of=/dev/null count=1 bs=1 > /dev/null 2>&1
if [ "$?" -ne "0" ] ; then
  echo you do not have permissions to eject the disk: $dev
  if [ "$(id -u)" != "0" ]; then
    echo maybe you need to run as root?
  fi
  exit
fi

if [ ! -r ./pluto.frm ] ; then
  echo "can not find the pluto.frm in the currect directory"
  exit
fi
if [ ! -r ./boot.frm ] ; then
  echo "can not find the boot.frm in the currect directory"
  exit
fi

# Look in the common places
if [ "$(grep $HOST ~/.ssh/config 2>/dev/null  | wc -l)" -eq "0" \
  -a "$(grep $HOST /etc/ssh/ssh_config 2>/dev/null  | wc -l)" -eq "0" 	] ; then
  echo can not find $HOST in either ~/.ssh/config or /etc/ssh/ssh_config
  echo remember - I am running as root, so ~/ might be /home/root/ (try sudo -s)
fi

SERIAL=$(grep -A 1 "<td>Serial</td>" /media/analog/PlutoSDR/info.html | \
		tail -1 | \
		sed -e 's/^.*<td>//' -e 's/<\/td>//')

echo "Disk   : $disk"
echo "Device : $dev"
echo "Serial : $SERIAL"
echo updating kernel and ramfs
echo "*** DO NOT UNPLUG"

cp ./pluto.frm $disk && eject $dev && sleep 1
wait_for_pluto 300
reset_pluto
echo updating FPGA image and bootloaders on $disk $dev
echo "*** DO NOT UNPLUG"
cp ./boot.frm $disk && eject $dev && sleep 1
wait_for_pluto 120
reset_pluto

there=$(ssh_cmd '/usr/sbin/fw_printenv' | grep attr_name | wc -l)
if [ "$there" -gt "0" ] ; then
    ssh_cmd 'echo 0x037 > /sys/kernel/debug/iio/iio:device1/direct_reg_access'
    device_id=$(ssh_cmd 'cat /sys/kernel/debug/iio/iio:device1/direct_reg_access')
    if [ "p${device_id}" = "p0xA" ] ; then
	echo updating to AD9364
        ssh_cmd '/usr/sbin/fw_setenv attr_name compatible'
        ssh_cmd '/usr/sbin/fw_setenv attr_val ad9364'
        reset_pluto
    fi
fi 

echo Done


